
<div class="container">

    <?php
        $collecton = $this->payload->getCollection();
    ?>
    <?php foreach ($collecton as $key => $value): ?>

    <h2><a href="<?= "https://www.swissbib.ch/Record/" . $value->getId()?>"  target="_blank    " ><?= $value->getId() ?></a></h2>
		<ul class="nav nav-tabs" id="<?= "-" . $value->getId() . "-serializations" ?>">
          <li><a href="<?= "#-" . $value->getId() . "-serialMF" ?>" data-toggle="tab">RDF/XML - MF (Nicolas)</a></li>
		  <li><a href="<?= "#-" . $value->getId() . "-rdfa" ?>" data-toggle="tab">RDFa</a></li>
		  <li><a href="<?= "#-" . $value->getId() . "-jld" ?>" data-toggle="tab">JLD</a></li>
		  <li><a href="<?= "#-" . $value->getId() . "-nt" ?>" data-toggle="tab">NT</a></li>
		  <li><a href="<?= "#-" . $value->getId() . "-ttl" ?>" data-toggle="tab">TTL</a></li>
		</ul>

        <div class="tab-content">
            <div class="tab-pane active" id="<?= "-" . $value->getId() . "-serialMF" ?>">
                <pre>
                <?= htmlspecialchars($value->getFullRecord()) ?>
                </pre>
            </div>
            <div class="tab-pane active" id="<?= "-" . $value->getId() . "-rdfa" ?>">
                content RDFa
            </div>

            <div class="tab-pane" id="<?= "-" . $value->getId() . "-jld" ?>">
                <pre>
                    <?= htmlspecialchars($value->getRecordJSONLD()) ?>
                </pre>

            </div>

            <div class="tab-pane" id="<?= "-" . $value->getId() . "-nt" ?>">
                <pre>
                    <?= htmlspecialchars($value->getNTriples()) ?>
                </pre>
            </div>

            <div class="tab-pane" id="<?= "-" . $value->getId() . "-ttl" ?>">
                <pre>
                    <?= htmlspecialchars($value->getTurtle()) ?>
                </pre>
            </div>
        </div>


        <script language="JavaScript">

            $(function() {
                $(<?= "'#-" . $value->getId() . "-serializations  a:first'" ?>).tab('show');
            });



       </script>

    <?php endforeach; ?>




</div>
